### ISSUE TITLE
cant wait for bot to reply

### ISSUE THREAD

**Issue by KlyukinSA** [vb64/telemulator3#28]
trying to send `message` and instantly receive `reply`:
```
    send_command(chat, message, user)
    sleep(0.05)
    assert reply in str(chat.history.messages[iteration])
```
but without `sleep` this fails assert:
```
KeyError: 2
```
 (iteration==2)

**Comment by vb64** [comment]
Did you instantiate the bot with the threaded=False parameter as shown in the [readme](https://github.com/vb64/telemulator3/blob/main/README.md#usage)?

```python
from telebot import TeleBot

bot = TeleBot('xxx-yyy-zzz', threaded=False)
```

**Comment by KlyukinSA** [comment]
> Did you instantiate the bot with the threaded=False parameter as shown in the [readme](https://github.com/vb64/telemulator3/blob/main/README.md#usage)?

no. i even import `bot` from other file

now i do so
```
from main import bot

bot.threaded = False # so as not to sleep

telemul = Telemulator()
telemul.set_tested_bot(bot, username='my_bot', name='My Bot')
```
and it works. but this seems to be the wrong architecture for testing

**Comment by vb64** [comment]
what do you mean as right architecture for testing?

**Comment by KlyukinSA** [comment]
> what do you mean as right architecture for testing?

test the object as it is given to us

**Comment by vb64** [comment]
it's impossible

passed object can be linked to private corporate resources. networks, databases and so on.

this case cant be implemetated in the public common test code. you must write your own code thats implement this cases.
